/bin/bash: /home/s1952889/miniconda3/envs/prompt/lib/libtinfo.so.6: no version information available (required by /bin/bash)
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/s1952889/miniconda3/envs/prompt/lib/python3.11/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/s1952889/miniconda3/envs/prompt/lib/python3.11/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
        ^^^^^^^^^
AttributeError: 'NativePathHandler' object has no attribute '_evt'
Namespace(config_file='visual_prompt_tuning/configs/prompt/cub.yaml', train_type='prompt', opts=['MODEL.TYPE', 'vit', 'DATA.BATCH_SIZE', '64', 'MODEL.PROMPT.NUM_TOKENS', '50', 'MODEL.PROMPT.DEEP', 'True', 'MODEL.PROMPT.DROPOUT', '0.1', 'DATA.FEATURE', 'sup_vitb16_imagenet21k', 'DATA.NAME', 'vtab-kitti(task="closest_vehicle_distance")', 'DATA.NUMBER_CLASSES', '4', 'DATA.CROPSIZE', '224', 'MODEL.MODEL_ROOT', 'visual_prompt_tuning/model_root', 'DATA.DATAPATH', 'visual_prompt_tuning/data_path', 'OUTPUT_DIR', 'visual_prompt_tuning/output_dir'])
Traceback (most recent call last):
  File "/home/s1952889/final-project/implementation/visual_prompt_tuning/tune_vtab.py", line 291, in <module>
    main(args)
  File "/home/s1952889/final-project/implementation/visual_prompt_tuning/tune_vtab.py", line 282, in main
    cfg = setup(args, lr, wd, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1952889/final-project/implementation/visual_prompt_tuning/tune_vtab.py", line 181, in setup
    cfg = setup_part(args, lr, wd, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1952889/final-project/implementation/visual_prompt_tuning/tune_vtab.py", line 173, in setup_part
    cfg.SEED = seed
    ^^^^^^^^
  File "/home/s1952889/miniconda3/envs/prompt/lib/python3.11/site-packages/fvcore/common/config.py", line 157, in __setattr__
    super().__setattr__(name, val)
  File "/home/s1952889/miniconda3/envs/prompt/lib/python3.11/site-packages/yacs/config.py", line 155, in __setattr__
    _assert_with_logging(
  File "/home/s1952889/miniconda3/envs/prompt/lib/python3.11/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'numpy.int64'> for key SEED; valid types = {<class 'int'>, <class 'str'>, <class 'NoneType'>, <class 'list'>, <class 'float'>, <class 'tuple'>, <class 'bool'>}
